export const ROUTES = {
  home: '/',
  about: '/about',
  academics: '/academics',
  admissions: '/admissions',
  studentLife: '/student-life',
  services: '/services',
  news: '/news',
  newsDetail: '/news/:id',
  gallery: '/gallery',
  contact: '/contact',
  login: '/login',
  dashboard: '/dashboard',
  studentDashboard: '/dashboard/student',
  studentFees: '/dashboard/student/fees',
  studentResults: '/dashboard/student/results',
  studentAssignments: '/dashboard/student/assignments',
  studentVirtualClass: '/dashboard/student/virtual-class',
  teacherDashboard: '/dashboard/teacher',
  teacherAssignments: '/dashboard/teacher/assignments',
  teacherResults: '/dashboard/teacher/results',
  teacherClasses: '/dashboard/teacher/classes',
  adminDashboard: '/dashboard/admin',
  adminStudents: '/dashboard/admin/students',
  adminTeachers: '/dashboard/admin/teachers',
  adminAdmissions: '/dashboard/admin/admissions',
  adminFees: '/dashboard/admin/fees',
  adminResults: '/dashboard/admin/results',
  adminAssignments: '/dashboard/admin/assignments',
  adminVirtualClass: '/dashboard/admin/virtual-class',
  adminNews: '/dashboard/admin/news',
  adminNewsPreview: '/dashboard/admin/news/preview',
  adminSettings: '/dashboard/admin/settings',
  notFound: '*',
} as const;

export type AppRouteKey = keyof typeof ROUTES;
