import { Link } from 'react-router-dom';
import { Layout } from '@/components/layout/Layout';
import { Container } from '@/components/ui/Container';
import { PageHero } from '@/components/ui/PageHero';
import { SampleNotice } from '@/components/ui/SampleNotice';
import { galleryImages } from '@/data/gallery';
import { ROUTES } from '@/routes/paths';
import { ChevronRight } from 'lucide-react';

const experiences = [
  { title: 'Clubs & Societies', text: 'Explore interests, work with peers and try new skills in a supportive setting.', image: 'https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1000&q=80' },
  { title: 'Sports & Recreation', text: 'Take part in activities that encourage teamwork, healthy habits and confidence.', image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1000&q=80' },
  { title: 'Cultural Activities', text: 'Celebrate creativity, community and the many stories students bring to school.', image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1000&q=80' },
];

export const StudentLifePage = () => (
  <Layout>
    <PageHero eyebrow="Life at school" title="A community to learn and belong" text="School life extends beyond lessons, helping students build friendships, confidence and a sense of possibility." image="https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1800&q=85" />
    <section className="py-16 sm:py-20"><Container className="grid items-center gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-700">Everyday growth</p><h2 className="mt-3 text-3xl font-extrabold">More than a timetable</h2><p className="mt-4 leading-relaxed text-muted">Students learn through shared experiences: solving problems together, discovering interests, expressing ideas and caring for their community. We aim to make school a place where every child has room to contribute and grow.</p><div className="mt-5"><SampleNotice>School-specific schedules and activity details await confirmation.</SampleNotice></div></div><img src={galleryImages[1].color} alt="Students in a classroom, sample image" loading="lazy" className="aspect-[4/3] w-full object-cover" /></Container></section>
    <section className="bg-cream py-16 sm:py-20"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-widest text-brand-700">Find your place</p><h2 className="mt-3 text-3xl font-extrabold">Ways to get involved</h2><p className="mt-3 text-muted">A balanced school experience includes space for teamwork, creativity and play.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{experiences.map((item) => <article key={item.title} className="border border-line bg-white"><img src={item.image} alt={`${item.title}, sample image`} loading="lazy" className="aspect-[16/10] w-full object-cover" /><div className="p-6"><h3 className="text-xl font-extrabold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{item.text}</p></div></article>)}</div><div className="mt-5"><SampleNotice>Activity descriptions and images are illustrative placeholders.</SampleNotice></div></Container></section>
    <section className="py-16 sm:py-20"><Container className="grid gap-10 md:grid-cols-2"><article className="border-t-2 border-brand-400 pt-5"><p className="text-xs font-bold uppercase tracking-widest text-brand-700">Boarding life</p><h2 className="mt-3 text-2xl font-extrabold">A supported home away from home</h2><p className="mt-3 text-sm leading-relaxed text-muted">Boarding information should explain accommodation, supervision, meals, study routines, activities and welfare. Please contact the school for confirmed details.</p><Link to={ROUTES.services} className="mt-5 inline-flex items-center gap-1 font-bold text-brand-700">Explore accommodation <ChevronRight aria-hidden="true" size={16} /></Link></article><article className="border-t-2 border-brand-400 pt-5"><p className="text-xs font-bold uppercase tracking-widest text-brand-700">Student support</p><h2 className="mt-3 text-2xl font-extrabold">Care for the whole learner</h2><p className="mt-3 text-sm leading-relaxed text-muted">Academic support, guidance, mentoring and welfare help students navigate challenges and make the most of their time at school.</p><Link to={ROUTES.contact} className="mt-5 inline-flex items-center gap-1 font-bold text-brand-700">Contact the school <ChevronRight aria-hidden="true" size={16} /></Link></article></Container></section>
    <section className="bg-brand-900 py-14 text-white"><Container className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest text-lime-accent">A closer look</p><h2 className="mt-2 text-2xl font-extrabold">See moments from our community</h2></div><Link to={ROUTES.gallery} className="inline-flex w-fit items-center gap-2 rounded bg-lime-accent px-5 py-3 font-bold text-brand-900">Visit the gallery <ChevronRight aria-hidden="true" size={16} /></Link></Container></section>
  </Layout>
);
